### ISSUE TITLE
import wirft fehler

### ISSUE THREAD

**Issue by marcuspappik** [radscheit/COAL-client#1]
import in der server.js wirft "unexpected reserved word" error

**Comment by radscheit** [comment]
Gibt es zu der Fehlermeldung noch weitere Details?

**Comment by marcuspappik** [comment]
`import {crawlImages} from './src/crawler.js';
^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
`

**Comment by radscheit** [comment]
ersetze mal die beiden imports in server.js durch 

```
System.import('./src/crawler.js').then(function(m) {
console.log(m);
m.crawlImages(url, writeOutput);
});
System.import('./src/rdf_parser.js').then(function(n) {
console.log(n);
n.constructParser(url);
n.parse(url);
});
```

und dann lösche die drei funktionsaufrufe in den zeilen darunter

**Comment by radscheit** [comment]
Vielleicht sollten wir beide Versionen über Exception-Handling einbauen, was meint ihr?

**Comment by Lando-L** [comment]
Ich hatte vergessen das README umzuschreiben. Mit den neuen Instructions(development) sollte das klappen
