### ISSUE TITLE
Warum wird die Webpack Dependencie nicht über die package.json gelöst?

### ISSUE THREAD

**Issue by radscheit** [radscheit/COAL-client#3]
![bildschirmfoto 2016-05-16 um 15 21 17](https://cloud.githubusercontent.com/assets/6578648/15290611/ed7fb312-1b79-11e6-93fe-d197cbccba4e.png)

**Comment by radscheit** [comment]
Habe es schnell selbst gemacht.

**Comment by Lando-L** [comment]
Weil webpack-dev-server global installiert werden muss. Deshalb auch -g

**Comment by radscheit** [comment]
Bei mir funktionierte es erst, als ich auf --global verzichtete.

**Comment by radscheit** [comment]
Wenn es dir wirklich auf das `--global` nakommt könntets du das auch als `preinstall` in der package.json definieren: https://docs.npmjs.com/misc/scripts
